---
name: dummy

releases:
- name: bosh-docker-cpi
  url: file:///opt/bosh/release/dev_releases/bosh-docker-cpi/bosh-docker-cpi-0+dev.1.tgz
- name: dummy
  url: file:///opt/bosh/downloads/dummy-0+dev.1.tgz

resource_pools:
- name: default
  network: default
  stemcell:
    url: file:///opt/bosh/downloads/bosh-stemcell-2776-warden-boshlite-ubuntu-trusty-go_agent.tgz
    # from https://s3.amazonaws.com/bosh-warden-stemcells/bosh-stemcell-2776-warden-boshlite-ubuntu-trusty-go_agent.tgz

networks:
- name: default
  type: dynamic

cloud_provider:
  template:
    name: cpi
    release: bosh-docker-cpi
  mbus: https://nats:nats@0.0.0.0:6868
  properties:
    cpi:
      mbus: https://nats:nats@0.0.0.0:6868

jobs:
- name: dummy
  instances: 1
  templates:
  - {name: dummy_with_properties, release: dummy}
  - {name: cpi, release: bosh-docker-cpi}
  resource_pool: default
  networks:
  - name: default
  properties:
    echo_value: hello
